### PR TITLE
talos support

### PR DESCRIPTION
**Pull request by Protryon**
Okay, I'll be honest, I didn't see #69 until I began to open this PR.

The approach here is self-contained setns via forking. This avoids the issue of being unable to set a mount namespace in a multithreaded process (not to mention needing to stop the world for thread safety).

There are certainly some improvements to be made here -- I don't write a lot of Go and didn't want to spend the time to perfect this if it has no chance of merging. Let me know if it's worth some more cleanup.

I'll open a corresponding PR for longhorn-manager as well. Tested and working with Talos v1.5.4.

### CODE REVIEW

**Comment by ccben87** [comment]
Hi @Protryon, some of us have been impatiently waiting on #69 for some time now. I really need to get something up and running ASAP. Do you think it's feasible to implement your change and then move to whatever gets officially merged when it gets merged? If so would you be kind enough to please advise what needs to be done to get this to work, is it just building go-iscsi-helper? Are you please able to advise how to configure Talos to use it?

**Comment by Protryon** [comment]
> Hi @Protryon, some of us have been impatiently waiting on #69 for some time now. I really need to get something up and running ASAP. Do you think it's feasible to implement your change and then move to whatever gets officially merged when it gets merged? If so would you be kind enough to please advise what needs to be done to get this to work, is it just building go-iscsi-helper? Are you please able to advise how to configure Talos to use it?

I need to push a few more changes up -- I've been integration testing on my homelab. I've got longhorn-manager up and running, provisioning volumes, but they are not successfully attaching yet -- IIRC manager was having issues with intermittent stalling, this stuff should be written in C not Go post-fork, and I might have to pull that trigger. Still working on debugging, I should have some time to work on it more this weekend, busy with work atm. I'll push up to my fork for this and longhorn-manager now if you want to take a look.

**Comment by innobead** [comment]
cc @c3y1huang

**Comment by innobead** [comment]
Thanks @ccben87 for the contribution. Talos has been done in https://github.com/longhorn/longhorn/issues/3161. 

Closing this PR, but feel free to contribute if anything you need in the future. Thanks!

**Pull request closed without merging**
